name: Build
on: [push]
jobs:
  test-app:
    name: Test app.py with Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Pylint
        run: pip install pylint
      - name: Test app.py with Pylint and Flask
        run: |
          pip install pylint flask
          pylint app.py
      - name: Run Pylint on app.py
        run: pylint app.py
